# Needed - latest updates, reboot, ansible, terraform, aws cli
---
- hosts: servers
  become: true

  tasks:
  name: Update Server
  apt:
    name: "*"
    state: latest
    update_cache: true


  name: Reboot and wait
  reboot:
    reboot_timeout: 3600

  name: Install Packages
  apt:
    pkg:
    - ansible
    - terraform
    - awscli
    state: latest
    update_cache: true
    cache_valid_time: 3600